from enum import Enum


class PrayerTimeCalculationMethod(Enum):
    SHIA = 0
    UNIV_ISLAMIC_SCIENCE_KARACHI = 1
    ISLAMIC_SOCIETY_N_AMERICA = 2
    MUSLIM_WORLD_LEAGUE = 3
    UMM_AL_QURA_UNIVERSITY = 4
    EGYPTIAN_GENERAL_AUTHORITY = 5
    INSTITUTE_OF_GEOPHYSICS = 7
    GULF_REGION = 8
    KUWAIT = 9
    QATAR = 10
    MAJLIS_UGAMA_ISLAM_SINGAPURA = 11
    UNION_ORGANIZATION_ISLAMIC_DE_FRANCE = 12
    DIYANET_ISLERI = 13
    SPIRITUAL_ADMINISTRATION_RUSSIA = 14